version: '3'
services:
  user-service:
    restart: on-failure
    image: user-service
    build: 
      context: ./
    ports:
      - "3000:3000"
    networks:
      - kwetter
    env_file: ./.env
networks:
  kwetter:
    driver: bridge

volumes: 
  db-config:
  db-data:
